### ISSUE TITLE
2024 - Roadmap

### ISSUE THREAD

**Issue by 22388o** [BitSwap-BiFi/Bitswap-core#1]
**Pre Beta**

- [x] Testnet
- [x] LDK support
- [x] Swap and AMM
- [x] LP
- [x] Package.json
- [x] Open source
- [X] BTC/USDT pair
- [x] Stop Loss
- [x] Unit Test

**Beta**
 
- [x] Swaps on-chain with DLCs
- [x]  Compile code
- [x] Release Official Beta
